Augments colcon pkg with dependencies from pyproject file.
UrbanMachine/colcon-poetry-ros pull request #38
Opened 2023-07-10 12:50 UTC by francocipollone

Related to #37 

### Summary

This PR introduces the ability to indicate the colcon/ros dependencies of the project via the `pyproject.toml` file.
Otherwise, dependencies for the package aren't loaded up, and the ordering when building isn't respected

### Use

Add to `pyproject.toml` the following section:

```toml
[colcon-package]
depend = ["another_pkg_1"]   # This will add to both `build_depend` and `exec_depend` following `package.xml` standards
build_depend = ["another_pkg_2"]
exec_depend = ["another_pkg_3"]
test_depend = ["another_pkg_4"]
```

2023-07-10 16:13 UTC, velovix requested changes
Thank you for doing this!

2023-07-10 16:13 UTC, velovix commented on colcon_poetry_ros/package_augmentation/poetry.py
> +    _PACKAGE_SECTION = "colcon-package"
We already have a custom section in the `pyproject.toml` for specifying data files, named `tool.colcon-poetry-ros.data-files`. Could we change this section to fit that convention? Maybe `tool.colcon-poetry-ros.dependencies`?

2023-07-10 16:16 UTC, francocipollone commented on colcon_poetry_ros/package_augmentation/poetry.py
> +    _PACKAGE_SECTION = "colcon-package"
Oh yeah makes sense!
Done!

2023-07-10 22:14 UTC, velovix approved these changes

2023-07-10 22:14 UTC, merged

2023-07-11 09:56 UTC, francocipollone commented
Thanks @velovix for the prompt review and merge and also for adding documentation I missed. 💯 

Are you planning a patch/minor release shortly to incorporate this changes?